eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@atlas.zcl5mit.mongodb.net/?retryWrites=true&w=majority
      host: ac-8juespq-shard-00-01.zcl5mit.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true
